export const kompyuterStoli = [
    {
        id: 1,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-1.jpg',
        price: '130',
    },
    {
        id: 2,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-2.jpg',
        price: '120',
    },
    {
        id: 3,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-3.jpg',
        price: '150',
    },
    {
        id: 4,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-4.jpg',
        price: '110',
    },
    {
        id: 5,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-5.jpg',
        price: '130',
    },
    {
        id: 6,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-6.jpg',
        price: '140',
    },
    {
        id: 7,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-7.jpg',
        price: '120',
    },
    {
        id: 8,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-8.jpg',
        price: '150',
    },
    {
        id: 9,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-9.jpg',
        price: '110',
    },
    {
        id: 10,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-10.jpg',
        price: '150',
    },
    {
        id: 11,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-11.jpg',
        price: '120',
    },
    {
        id: 12,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-12.jpg',
        price: '130',
    },
    {
        id: 13,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-13.jpg',
        price: '130',
    },
    {
        id: 14,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-14.jpg',
        price: '140',
    },
    {
        id: 15,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-15.jpg',
        price: '120',
    },
    {
        id: 16,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'komp-16.jpg',
        price: '110',
    },
]