export const oshxona = [
    {
        id: 1,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-1.jpg',
        price: '130',
    },
    {
        id: 2,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-2.jpg',
        price: '120',
    },
    {
        id: 3,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-3.jpg',
        price: '110',
    },
    {
        id: 4,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-4.jpg',
        price: '100',
    },
    {
        id: 5,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-5.jpg',
        price: '150',
    },
    {
        id: 6,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-6.jpg',
        price: '140',
    },
    {
        id: 7,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-7.jpg',
        price: '110',
    },
    {
        id: 8,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-8.jpg',
        price: '120',
    },
    {
        id: 9,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-9.jpg',
        price: '130',
    },
    {
        id: 10,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-10.jpg',
        price: '140',
    },
    {
        id: 11,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-11.jpg',
        price: '150',
    },
    {
        id: 12,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-12.jpg',
        price: '120',
    },
    {
        id: 13,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-13.jpg',
        price: '130',
    },
    {
        id: 14,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-14.jpg',
        price: '110',
    },
    {
        id: 15,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-15.jpg',
        price: '120',
    },
    {
        id: 16,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Kuxni-mebel-16.jpg',
        price: '130',
    },
]