export const stol = [
    {
        id: 1,
        dirLink: 'Stol-1/',
        width: '186',
        height: '100',
        color: ['#6d4117', 'black', 'blue', 'yellow'],
        link: ['Stol-1.jpg', 'Stol-1 black.jpg', 'Stol-1 blue.jpg', 'Stol-1 yellow.jpg'],
        price: '130',
    },
    {
        id: 2,
        dirLink: 'Stol-2/',
        width: '186',
        height: '100',
        color: ['#6d4117', 'black', 'blue', 'yellow'],
        link: ['Stol-2.jpg', 'Stol-2 black.jpg', 'Stol-2 blue.jpg', 'Stol-2 yellow.jpg'],
        price: '130',
    },
    {
        id: 3,
        dirLink: 'Stol-3/',
        width: '186',
        height: '100',
        color: ['#6d4117', 'black', 'blue', 'yellow'],
        link: ['Stol-3.jpg', 'Stol-3 black.jpg', 'Stol-3 blue.jpg', 'Stol-3 yellow.jpg'],
        price: '130',
    },
    {
        id: 4,
        dirLink: 'Stol-4/',
        width: '186',
        height: '100',
        color: ['#6d4117', 'black', 'blue', 'yellow'],
        link: ['Stol-4.jpg', 'Stol-4 black.jpg', 'Stol-4 blue.jpg', 'Stol-4 yellow.jpg'],
        price: '130',
    },
    {
        id: 5,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Stol-5.webp',
        price: '130',
    },
    {
        id: 6,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Stol-6.jpg',
        price: '130',
    },
    {
        id: 7,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Stol-7.webp',
        price: '130',
    },
    {
        id: 8,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Stol-8.jpg',
        price: '130',
    },
    {
        id: 9,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Stol-9.jpg',
        price: '130',
    },
    {
        id: 10,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Stol-10.jpg',
        price: '130',
    },
    {
        id: 11,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Stol-11.jpg',
        price: '130',
    },
    {
        id: 12,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Stol-12.jpg',
        price: '130',
    },
    {
        id: 13,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Stol-13.jpg',
        price: '130',
    },
    {
        id: 14,
        dirLink: '',
        width: '186',
        height: '100',
        color: [],
        link: 'Stol-14.jpg',
        price: '130',
    },
]