export const yumshoqMebel = [
    {
        id: 1,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-1.jpg',
    },
    {
        id: 2,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-2.jpg',
    },
    {
        id: 3,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-3.jpg',
    },
    {
        id: 4,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-4.jpg',
    },
    {
        id: 5,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-5.jpg',
    },
    {
        id: 6,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-6.jpg',
    },
    {
        id: 7,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-7.jpg',
    },
    {
        id: 8,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-8.jpg',
    },
    {
        id: 9,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-9.jpg',
    },
    {
        id: 10,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-10.jpg',
    },
    {
        id: 11,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-11.jpg',
    },
    {
        id: 12,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-12.jpg',
    },
    {
        id: 13,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-13.jpg',
    },
    {
        id: 14,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-14.jpg',
    },
    {
        id: 15,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-15.jpg',
    },
    {
        id: 16,
        dirLink: '',
        color: [],
        link: 'yumshoq-mebel-16.jpg',
    },
]